### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by kengruven** [libgit2-racket/libgit2#3]
[Searching for "libgit2"](https://docs.racket-lang.org/search/index.html?q=libgit2) on docs.racket-lang.org turns up nothing.  [The package page](https://pkgs.racket-lang.org/package/libgit2) appears to have the most recent hash but clicking "Documentation" goes to a Racket documentation page with the old `git_revwalk_next` interface.

Is this related to #2?  Or do we just need to wait for some process to catch up?

**Comment by LiberalArtist** [comment]
The build failure from https://github.com/libgit2-racket/libgit2/issues/2 prevents the current docs from generating, which makes https://github.com/libgit2-racket/libgit2/issues/2 an especially high priority.

Installing the package will build the documentation locally.

A separate problem is that I neglected to update the documentation for `git_revwalk_next` in https://github.com/libgit2-racket/libgit2/pull/1.

**Comment by LiberalArtist** [comment]
The docs have built at https://pkgs.racket-lang.org/package/libgit2 using https://github.com/libgit2-racket/libgit2/pull/6 , so this is fixed, though https://github.com/libgit2-racket/libgit2/issues/2 is still an issue.
